### ISSUE TITLE
Alternate USB Connector

### ISSUE THREAD

**Issue by steveschnepp** [dwillmore/TSSOP20_breakout#1]
Would it be possible to map an alternate micro/mini usb connector under the existing usb-c one ? 

So one has the 2 choices, as soldering usb-c is not a rookie task.

**Comment by steveschnepp** [comment]
Closing, as we can just use the test pads on the side

**Comment by dwillmore** [comment]
Just to add some notes here.  The USB-C connector I used is the middle of the road complexity one.  It only had the power, ground, CC, SBC, and data lines available.  It's not the full up one with the high speed data pairs, but it's also not the really simplified one that lacks the data lines.  I don't think there's room on the reverse side for the simplified connector.  You'd need to make a variant of this board.

I have soldered dozens of these USB-C connectors on boards using this pinout and it's not hard to do with just a soldering iron, normal solder, and some solder wick.  It's easier with a fine paste applicator and air, but I've always need *some* level of cleanup with wick--possibly that's a lack of skill issue on my part.  So, I'd say it's not trivial, but it's not that hard.  All SMT soldering is easier with lots of flux, though.

**Comment by steveschnepp** [comment]
I'm also wondering about the price overhead of ordering the pcb with just the usb-c presoldered.

As it is the only one i don't manage with the iron

**Comment by dwillmore** [comment]
Have you tried it with a litle flux and some braid?  Just solder all the pins well with extra flux, then apply a little flux to some braid and suck out any extra solder.   I've never had any boards assembled for me, so I can't advise you on any of that.
