### ISSUE TITLE
Stencil

### ISSUE THREAD

**Issue by petiepooo** [dwillmore/TSSOP20_breakout#3]
Would be awesome to have a pre-generated solder stencil ready to download.  I love the way a board comes together on a hotplate or hot air rework station when using solder paste and a stencil.

**Comment by dwillmore** [comment]
Given the low volume nature of the use of this board, I didn't think anyone would want a stencil for them, but I can certainly generate the file and add it to the repo.

**Comment by dwillmore** [comment]
Okay, good news!  It seems the workflow I use--as recommended by JLCPCB--generates the stencil info.  So the .zip file in the fab_files directory has the required info already.  If you want to order a stencil, you're good to go with the info there!

There are a lot of cautions you need to know when ordering a stencil--like don't order the full sized or framed ones as they're huge and cost a ton.  You only need the little cut down one for home production of a board at a time.  I know people who've made this mistake and not only paid way more than they needed to, but got a stencil that was so large it was hard to use.  Full sized stencils are meant for automated paste application machines.  And if you have one of those, you're not using this design. :)

**Comment by petiepooo** [comment]
Thanks much!
